name: Daily NSE EMA Automation

on:
  schedule:
    - cron: '30 3 * * *'  # Runs every day at 9:00 AM IST (03:30 UTC)
  workflow_dispatch:      # Allows manual run from GitHub

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install yfinance ta pandas

    - name: Run NSE EMA Script
      env:
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      run: python nse_ema_analysis.py
